language: php
php:
- '5.6'
- '7.2'
- '7.3'
env:
- SWVER=5.4
- SWVER=5.5
- SWVER=5.6
matrix:
  exclude:
    - php: '5.6'
      env: SWVER=5.6
addons:
  apt:
    update: true
    packages: ant
services:
- mysql
before_script:
- git clone --depth=1 -b $SWVER https://github.com/shopware5/shopware.git /tmp/shopware
- cd ..
- cd /tmp/shopware
- ant -f build/build.xml -Ddb.user=root -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
- cp -R /home/travis/build/PAYONE-GmbH/shopware-5/Frontend/MoptPaymentPayone /tmp/shopware/engine/Shopware/Plugins/Default/Frontend
- cd /tmp/shopware
- ls engine/Shopware/Plugins/Default/Frontend
- php bin/console sw:plugin:refresh
- php bin/console sw:plugin:list
- php bin/console sw:plugin:install MoptPaymentPayone
- php bin/console sw:plugin:activate MoptPaymentPayone
- php bin/console sw:generate:attributes
- php bin/console orm:generate:proxies
- cd /tmp/shopware/tests
script:
- cd $TRAVIS_BUILD_DIR
- ant
before_deploy:
- export PACKAGE=$(ls *.zip)
- echo "Deploying $PACKAGE"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QAz+V29vAPDvhvGxXUQknW/wrnK3Bn1egDfA2PyKeAC9DDpniCe3dP7Zote3x7kqRNNuiN6W7TLAEZKcGXHnEjhLbxM5z4YeyJgL8Uwu583cUqOO8l9203orpsCu1sG23S7XsIjHSWvqCsOdzcIiAtIy7cn4M4JqWj0Bnrps5bkxYRPs5REOq7p3JmLfgguyRbqGG1qyt8HcpAcmCZvn1f5jZYbfnJWaeTiEX9LN6d7pFEOF93L5Gvu/IPj7Xq2dZIwBUKLQcN2JRQdHwtLQZmEcphKYbBt51B+XShW+wWeNhQ2K4ZIYVHAgDZqEv/nnAIb7VT4DXg5MnxmJbxI8iGnTMA83X0ZfYtYc8QcCkg5dFOoaM9C3iS2mU7p8XcxwL+WBlRICO8NDfe7rBLYDC+PMjRKeETMXntSru9VN3qCgPEFmU9MibA+NvFhzLiF5EdqX/NL8oaNTH09Kf2iCyDVzpOToNLnf1/TLnH0I5MDM4qzZtnQlmHca+i0uSfytTOPr/3MzzlxOCh44nF4ckfY0nr4jGJ/B1sV73kwdtPmJ4ETT3SbQEsOPV2KHLQQY3yjkYVHQoqHG2r6bB1Hci62FdIFqlxxD9mMpkcuw4kZTd5hGBj4vcVHet3BNFdtblAux0bj6HE+GWUrd2A7qQ60rGUnd6p9TVcLnM5pulwQ=
  file: 
  - "${PACKAGE}"
  on:
    repo: PAYONE-GmbH/shopware-5
    all_branches: true
    tags: true
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: BnPN3t23S+44tENFvtUJAFTYGMJcHmG973s5+xBlKvSRg59PTo6b7pgR6bbLt8hNT1FxocxbmVRkVbxX41JVNmQ6q6ezpcunMWTnikhVSx1suM7Y1Q35LNBcNgBqxrcGyGE3mmyVfYa2Siyy8HVmoNPXx/v5l2vn8pM4JnEQ0w45S/bwy1/rlsI4g0tQ8Rh1r/DR4TJUa/mCTQP0p4Vi0+L5b9vO3OCctwMqYSGA9E6Hgv+m8KMJcFut6FrcIw67lPmVbWhpl9j5HrxeXLAq5pLpPcBfR9QQTXzQshd4+ygqtzpxm444CHlIrvmdrtRFoGjDv3MVPTKKRp/vyrn/GxWziIHzV4u7vfUbCBHMYxGkuZZPxDCuDexuiLoyVo4vAKyRhBsUrse9EhYr1eVAFPkDa1VgUgwwjDv9HS012ipyFGK2FbL/Z0qi+d6/FONLOUFSI5vAVmVug4QtBiqdeN9glqzgknkEcn/5yZi0RBfehy7Zuo95HAW3J7b3e0kFbRG9duKxd9OlPhNQQOU1mLTPNDyfx7jC321247v0GBEra7Cw4FQB1mKG2BXxchz+yTny0tnHGBNqd9P/rv+op8LC5lfruiI4g5An7ykCdlN0BIHVHIuK5Cg4h8Vb44gO3dzEuU0nYX3WCXZOCIUCz9njjqXKFYbc9+FIiVusG0Y=
